### ISSUE TITLE
cannot set instance attribute inside function under timeout

### ISSUE THREAD

**Issue by trancyquan** [bitranox/wrapt_timeout_decorator#16]
Hi,
As shown as below code, if we set value for instance attribute x to 'y', the value still print as 'x'.
Is this a bug? Or i used it wrongly?

```
from wrapt_timeout_decorator import *

class Test():
    def __init__(self):
        self.x = 'x'

    @timeout(20)    
    def set_value(self):
        self.x = 'y'
        return None
    
    def get_value(self):
        return self.x
    
tmp = Test()
tmp.set_value()
print(tmp.get_value())
```

**Comment by bitranox** [comment]
I guess You used it on Windows, so main gets reloaded on "fake fork"
Please check the manual - the class needs to be in a seperate module, 
or it gets reloaded when windows makes the "fake fork" .
Check the Readme, Section "use with windows"

so change to : 
```
# my_timeout_test_class.py

from wrapt_timeout_decorator import *

class Test():
    def __init__(self):
        self.x = 'x'

    @timeout(20)    
    def set_value(self):
        self.x = 'y'
        return None
    
    def get_value(self):
        return self.x

```

```
# main.py

# PROJECT Imports
import my_timeout_test_class

function main():
    tmp=my_timeout_test_class.Test()
    tmp.set_value()
    print(tmp.get_value())

if __name__ == '__main__':
    main()

```

**Comment by trancyquan** [comment]
> I guess You used it on Windows, so main gets reloaded on "fake fork"
> Please check the manual - the class needs to be in a seperate module,
> or it gets reloaded when windows makes the "fake fork" .
> Check the Readme, Section "use with windows"
> 
> so change to :
> 
> ```
> # my_timeout_test_class.py
> 
> from wrapt_timeout_decorator import *
> 
> class Test():
>     def __init__(self):
>         self.x = 'x'
> 
>     @timeout(20)    
>     def set_value(self):
>         self.x = 'y'
>         return None
>     
>     def get_value(self):
>         return self.x
> ```
> 
> ```
> # main.py
> 
> # PROJECT Imports
> import my_timeout_test_class
> 
> function main():
>     tmp=my_timeout_test_class.Test()
>     tmp.set_value()
>     print(tmp.get_value())
> 
> if __name__ == '__main__':
>     main()
> ```

Thanks for replying. I tried this however it doesn't work on my windows machine. Still got value x.
Btw, it's ```def main()``` not ```function main()```

**Comment by bitranox** [comment]
ok , I can guess why - always remember that under windows the object is serialized and run in a seperate process - there is no other way. Also Results are serialized.
So ONLY put the decorator at the possibly most LOW LEVEL, even better OUTSIDE of classes, 
because the state of the new object is not transfered back to the original object (only the result).
If the Class can be serialized, You might try to return self. 

```
# my_timeout_test_class.py

from wrapt_timeout_decorator import *

class Test():
    def __init__(self):
        self.x = 'x'

    @timeout(20)    
    def _add_new_value_to_x_with_timeout(self):
        x = self.x + 'y'    # just to make it more interesting
        return x

    def set_value(self):
        self.x = self._add_new_value_to_x_with_timeout()
        return self.x     # always return something useful - its not costy
    
    def get_value(self):
        return self.x

```
