### ISSUE TITLE
Embedded Python 3.6.9 doesn't timeout when use_signals=False

### ISSUE THREAD

**Issue by ReallyNiceGuy** [bitranox/wrapt_timeout_decorator#18]
I am using the HEAD version of the GIT for testing, and it works fine with use_signals=True.
I can give you an excerpt of the C++ code, but it is basically directly from the python documentation.

Sample:

```python
from wrapt_timeout_decorator import *

@timeout(0.1,use_signals=False,exception_message='Function {function_name} ran for too long, aborted')
def ontimer():
    print("tick")
    while(True): pass
```
Is there any more information I can give you?

**Comment by bitranox** [comment]
did You put the definition of that ontimer() function outside the main context ? 
put it in another module, and import it. 
Its probably on windows and cant fork, right ?

**Comment by ReallyNiceGuy** [comment]
Thank you for your quick answer.
I am running in Linux.

This is what I did, complete:

```c++
  // Register setTimerFunction here.

  Py_Initialize();
  PyObject * main_module = PyImport_ImportModule("__main__");
  PyObject* global_symbol_table = PyModule_GetDict(main_module);
  PyRun_SimpleString(
                     "import sys\n"
                     "import os\n");
  if (!PyRun_FileEx(fp, filename, Py_file_input, global_symbol_table, global_symbol_table,1))
  {
    treatError();
    return false;
  }
...
PyObject* setTimerFunction(PyObject *self, PyObject *args)
{
  PyObject *temp;
  if (PyArg_ParseTuple(args, "O:set_timer_function", &temp))
  {
    if (temp == Py_None)
    {
      Py_XDECREF(m_timerFunction);
      m_timerInterval = 0;
      m_timerFunction = nullptr;
    }
    else if (PyCallable_Check(temp))
    {
      Py_INCREF(temp);
      Py_XDECREF(m_timerFunction);
      m_timerFunction=temp;
    }
    Py_RETURN_NONE;
  }
  PyErr_SetString(PyExc_TypeError, "parameter must be callable or None to disable");
  return nullptr;
}
...
  callTimer()
  {
    auto res = PyObject_CallObject(m_timerFunction,nullptr);
    if (!res)
    {
      treatError();
      return;
    }
    Py_XDECREF(res);
  }
``` 
I am guessing that I miss something in the environment initialization.
When I print __name__ from the script (before defining ontimer()), it does print "__main__"

**Comment by bitranox** [comment]
Dear Marco,
sorry I have no experience in C interfacing to python. 
What I can say is, that if using ``` signals = False ``` option, a new process will be forked.
So You need to guard as described in the documentation.

Try to put Your ```ontimer``` function into another module and import it from there,
not from ```__main__```.
And/Or guard with the famouse

```
#! python
import ....
import ontimer_module 
...

def main():
    ontimer_module.ontimer()


if __name__ == "__main__":
    main()
```

let me know !
Yours sincerely
Robert

**Comment by ReallyNiceGuy** [comment]
Hi, Robert.

I tested your suggestion, it also doesn't work.
I will debug further on my side. I might have some strange interactions with my application. If I can replicate the issue with a minimalist application, I will ping you again.

Thanks for your efforts.

**Comment by bitranox** [comment]
also try to set the timeout time to 1-2 seconds - especially on windows forking takes ages ... 
Robert

**Comment by ReallyNiceGuy** [comment]
This application runs only on Linux.
I created a minimalist test with the same initialization code, and it works just fine. So, I have some weird interaction with my application.

I guess we can close this thread.
Thanks again.

**Comment by ReallyNiceGuy** [comment]
Just so you know:

If I get a timeout error, I disable the script and call Py_FinalizeEx.
It then hangs won waitpid.

On my minimalist test, I get instead of the hang:
SystemError: <built-in method locked of _thread.lock object at 0x7f9bc119f760> returned a result with an error set

Python is not simple...

**Comment by ReallyNiceGuy** [comment]
I found the issue, on my side, but it might affect you:
I have a handler for SIGTERM that basically ignores it (not on purpose, it is a bug on my code).
So, if an application has a SIGTERM handler that doesn't terminate, the fork cannot be killed, so the Timeout will not work.

**Comment by bitranox** [comment]
Thanks Marco, i will note that in the manual !
