### ISSUE TITLE
wrap_helper.py breaks logging

### ISSUE THREAD

**Issue by undera** [bitranox/wrapt_timeout_decorator#20]
Due to `logging.basicConfig()` call inside `wrap_helper.py`, logging gets initialized without user's control, during import processing.  Thus, when interpreter reaches my application code, my logging initialization has no effect. This is surprising and undesired side effect that prevents me from using this library inside my app.

I believe logging initialization should be removed from global scope. If one needs the logging for debug purposes, he should initialize it inside `__main__` or unit test scope.

**Comment by bitranox** [comment]
You are right, I will take care of it.
благодарю за совет
Robert

**Comment by angadsingh** [comment]
seriously? this is so immature. please fix this.

**Comment by bitranox** [comment]
@angadsingh , sorry I have other more important things to do ATM - I will fix it as soon as I can.
Until then You might fork and fix it Yourself.

**Comment by bitranox** [comment]
logging.basicConfig() is removed.

**Comment by chrisimcevoy** [comment]
At time of writing the latest (pip installable) version on PyPI is 1.3.0 which has the `logging.basicConfig()` call in it.

Depending on your usage, you might work around the issue by changing this

```python
# foo.py
import logging
from wrapt_timeout_decorator import timeout  # logging.basicConfig() called inside here

logging.basicConfig(level=logging.DEBUG, ...)  # Your logging is broken


@timeout(30)
def long_running_func():
    ...
```

to this

```python
# foo.py
import logging

logging.basicConfig(level=logging.DEBUG, ...)  # Your logging config here is ok

from wrapt_timeout_decorator import timeout  # logging.basicConfig() called inside here but it doesn't break stuff


@timeout(30)
def long_running_func():
    ...
```

Just make sure you `import wrapt_timeout_decorator` *after* you call `logging.basicConfig()`.

**Comment by qqqqqwwwweeerr1gmail** [comment]
same with you.
