### ISSUE TITLE
BrokenPipeError while terminating a function that uses multiprocessing

### ISSUE THREAD

**Issue by Arjunsankarlal** [bitranox/wrapt_timeout_decorator#23]
Sometimes the function using multiprocessing stalls for no reason and consuming lot of CPU and memory and thereby hangs my webserver. So I used wrapt-timeout-decorator and it works cool and has solved my issue. 

But while the function is terminated because of timeout, the BrokenPipeError is happening since the pool is closed abruptly. Since the timeout error is raised first it is sent as a response. But BrokenPipeError occurs after a small delay say 1 second. So I tried if I can add a sleep somewhere, but the TimeOutError is thrown first, there is no way I could handle the BrokenPipeError. Is there any work around for this ?

**Comment by bitranox** [comment]
without further information that is hard to say.
But since You KNOW that it is a BrokenPipeError, You know also the scope in which function that Error occurs - 
so You need to wrap that relevant function into 

```
try:
   do_important_things()
   ....
except BrokenPoolError: 
   do_some_cleanup_to_handle_that_condition()
```

**Comment by Arjunsankarlal** [comment]
Hey thanks for the quick reply,

```
class TestModel:
    @staticmethod
    @timeout(dec_timeout=3)
    def build_model(x):
        try:
            out = do_something_expensive(x) # this function does the normal multiprocessing stuff
            return out
        except BrokenPipeError:
            logger.warning("Training broken")
            return None
```

I have reduced the timeout to simulate the scenario, so after three seconds, I get the timeout error for `build_model` function and it is been processed and returned as response. But only after that I get BrokenPipeError!

**Comment by bitranox** [comment]
You should use the timeout on the smallest scope possible,
so please try to track down WHICH part is hanging ... 

```

class TestModel:
    @staticmethod
    def build_model(x):
        try:
            out = do_something_expensive(x) # this function does the normal multiprocessing stuff
            return out
        except BrokenPipeError:
            logger.warning("Training broken")
            return None

def do_something_expensive(x) # this function does the normal multiprocessing stuff
    do_stuff()
    try: 
        do_stuff_that_might_timeout(x)
        do_more_stuff()
    except TimeoutError:
       cleanup...
    finally:
       whatever ...

@timeout(dec_timeout=3)
def do_stuff_that_might_timeout(x):
  ...
```

so move down the timeout decorator in the hirachy down as much as possible - probably to find out WHICH part is actually timing out !

the BrokenPipeError - do You have a traceback ? Is it within the timeout decorator ? 
Or is it somewere else ?

**Comment by bitranox** [comment]
BTW - I will make a new release this week, so I would be grateful if You can try, and give some tracebacks, etc ...

**Comment by bitranox** [comment]
Also try to save "x" - and call the function do_something_expensive(x) in a normal (non-multiprocessing) context - 
I guess that some data in "x" causes the function  do_something_expensive(x) to hang. 
So You need to investigate to find the real reason ....

**Comment by Arjunsankarlal** [comment]
Sure I will share the details in sometime. But as far as I have seen the exception is not because of the decorator. And regarding the hanging, it is actually inconsistent. Like to reproduce it I tried making the request with 10 different data('x') repeatedly. Each request would take say 1-2 mins with multiprocessing, after hours of load testing with the same data at a random point (after some 1000+ successfully served requests), the server won't respond to further requests and when I saw the processes running, one or two spawned processes would be in sleep state consuming large memory and CPU.

So the reason why I used the decorator at the outer scope was, I have the following scenario

```
class TestModel:
    @staticmethod
    def build_model(x):
        try:
            a,b = do_something_expensive_1(x) # this function does the normal multiprocessing stuff
            out2 = do_something_expensive_2(a) # this function does the normal multiprocessing stuff
            out3 = do_something_expensive_2(b) # this function does the normal multiprocessing stuff
            final_output = combine(out1, out2, out3)
            return final_output
        except BrokenPipeError:
            logger.warning("Training broken")
            return None
```

So the inner function would take varying time based on the data of x. But yeah, I will try the things you said, and try to use the decorator at the smallest scope and will let you know.

Also I would be grateful if you could share something you know about the multiprocessing worker stalling issue :)

**Comment by bitranox** [comment]
hm, I dont know Your program of course - but it seems the worker is hanging for some unknown reasons. 

But since the workers are running usually with a given (x), there can be only a few reasons it hangs.

Usually its some queue handling or locking issue - 

here, that might be a hint : 

https://stackoverflow.com/questions/28896055/multiprocessing-queue-hanging-when-process-dies
