### ISSUE TITLE
NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by Assile** [bitranox/wrapt_timeout_decorator#24]
Hi, I've run into quite a perplexing issue.
I've been trying to run the example code you provided:
```import time
from wrapt_timeout_decorator import *

@timeout(5)
def mytest(message):
    print(message)
    for i in range(1,10):
        time.sleep(1)
        print('{} seconds have passed'.format(i))

if __name__ == '__main__':
    mytest('starting')
```

Running it from a python file works as expected. However running it in Jupyter returns a NameError:
`NameError: name 'time' is not defined`

In both cases I am running python 3.7.6, Jupyter is running as installed from Anaconda3.
Removing the timeout decorator 'fixes' the issue, but that is of course the thing I want to use.

Do you know what might be the issue?
Best regards,
Assile

**Comment by bitranox** [comment]
Dear Assile,
of course You need to import the `time`module:

```
import time
from wrapt_timeout_decorator import *

@timeout(5)
def mytest(message):
    print(message)
    for i in range(1,10):
        time.sleep(1)
        print('{} seconds have passed'.format(i))

if __name__ == '__main__':
    mytest('starting')

```

yours sincerely

Robert

**Comment by Assile** [comment]
Ah my apologies, I seem to have only partially copied the code or copied a version with time imported in another cell.
Running this:
```
import time
from wrapt_timeout_decorator import *

@timeout(5)
def mytest(message):
    print(message)
    for i in range(1,10):
        time.sleep(1)
        print('{} seconds have passed'.format(i))

if __name__ == '__main__':
    mytest('starting')
```

Produces this:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-27cecca58c0a> in <module>
     10 
     11 if __name__ == '__main__':
---> 12     mytest('starting')

D:\Users\freek\anaconda3\envs\webscraping\lib\site-packages\wrapt\wrappers.py in __call__(self, *args, **kwargs)
    564         # wrapped using the staticmethod decorator.
    565 
--> 566         return self._self_wrapper(self.__wrapped__, self._self_instance,
    567                 args, kwargs)
    568 

D:\Users\freek\anaconda3\envs\webscraping\lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py in wrapper(wrapped, instance, args, kwargs)
    121             return wrapped(*wrap_helper.args, **wrap_helper.kwargs)
    122         else:
--> 123             return wrapped_with_timeout(wrap_helper)
    124     return wrapper
    125 

D:\Users\freek\anaconda3\envs\webscraping\lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py in wrapped_with_timeout(wrap_helper)
    129         return wrapped_with_timeout_signals(wrap_helper)
    130     else:
--> 131         return wrapped_with_timeout_process(wrap_helper)
    132 
    133 

D:\Users\freek\anaconda3\envs\webscraping\lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py in wrapped_with_timeout_process(wrap_helper)
    143     try:
    144         timeout_wrapper = Timeout(wrap_helper)
--> 145         return timeout_wrapper()
    146     except PicklingError:
    147         detect_unpickable_objects_and_reraise(wrap_helper.wrapped)

D:\Users\freek\anaconda3\envs\webscraping\lib\site-packages\wrapt_timeout_decorator\wrap_function_multiprocess.py in __call__(self)
     39             self.wait_until_process_started()
     40         if self.__parent_conn.poll(self.wrap_helper.dec_timeout_float):
---> 41             return self.value
     42         else:
     43             self.cancel()

D:\Users\freek\anaconda3\envs\webscraping\lib\site-packages\wrapt_timeout_decorator\wrap_function_multiprocess.py in value(self)
     63 
     64         if exception_occured:
---> 65             raise result
     66         else:
     67             return result

NameError: name 'time' is not defined
```

So it's not like I've not proplerly imported time, my apologies for that oversight.

**Comment by bitranox** [comment]
Dear Assile,

I can see that You work on windows. As explained in the manual we need to use multiprocessing on windows. 

Since windows can not fork (it does not support it), a "fork-like" behaviour is emulated by python. In order to spawn a new process, the environment (loaded modules, contents of variables, program state) needs to be copied.

The new process is spawned with a different `__name__` , thats why we guard the call to `main()` with the line `if __name__ == '__main__': ...`

I dont know the details of jupyter, how it handles initialisation and multiprocessing - but now it looks that 'time' is not imported in the spawned process.

You really need to investigate deeper - what ELSE is not copied into the spawned process ? 
Some states of (global) variables ?  etc.

My guessing : it is just an issue when You run jupyter locally on windows, on linux it will work.

a quick fix (but there might be many more, hidden issues) would be : 

```

import time
from wrapt_timeout_decorator import *

@timeout(5)
def mytest(message):
    # lets import time again, because jupyter mangles up the context on spawn (?)
    import time
    print(message)
    for i in range(1,10):
        time.sleep(1)
        print('{} seconds have passed'.format(i))

if __name__ == '__main__':
    mytest('starting')

```

but that it is not the fault of the timeout decorator, it is the fact that windows does not support ´fork´ ... and all the bad things caused by that.

**Comment by Assile** [comment]
Hi Bitranox,

Thank you for looking into this! I'll take a deeper dive once I get some more time to work on it.

That quick fix does indeed work, but there may indeed be many more issues hiding. I really need to just learn the full story of multiprocessing on windows when I have the time.
