### ISSUE TITLE
use timeout() but couldn't get the global variable 

### ISSUE THREAD

**Issue by MelonHjy** [bitranox/wrapt_timeout_decorator#25]
I use timeout() in a function(my pytest project),But when I debug,I saw the function couldn't get the global variable.
![image](https://user-images.githubusercontent.com/36230764/92195417-89f58080-ee9f-11ea-9f7b-c18f60d5558e.png)
![image](https://user-images.githubusercontent.com/36230764/92195573-f1133500-ee9f-11ea-84a2-cb5f94bca505.png)
And then I try to pass the global var as input to the function, and it doesn't get into the function
![image](https://user-images.githubusercontent.com/36230764/92195623-025c4180-eea0-11ea-87db-fbd1d86740dc.png)
![image](https://user-images.githubusercontent.com/36230764/92195799-6252e800-eea0-11ea-8371-29237b51f53b.png)
(But if I pass a str as input to the function,and  the str can print)Is there any work around for this ?

**Comment by bitranox** [comment]
Its under Windows, right ? 
You need to consider that a new process is started - with all the forking-like behaviour on windows (and real forking on linux).

Try to put the function `close_browser` into another module.

**Comment by MelonHjy** [comment]
Thank you for your answer.Yes, its under windows.But I don't know why you said 'Try to put the function close_browser into another module.' ?Probably its my statement  inaccurate。。The global variable assigned after the timeout decorator init,So when I start the project,the 'timeout' fork a new process(with a None global variable),and then the old process assigned the global variable,and when I call the function close_browser，it use the None global variable.Am I right to understand that？

**Comment by bitranox** [comment]
usually its a problem with windows forking, because the main context might not be restored completely on the new fork.
Just try to put the function in a seperate module - it might work then.
Dont use a global Variable in the main context - try to save the value in a seperate class property, which can be pickled, in a seperate module.
guard appropiately with : 
```
if __name__ == '__main__': 
    ...
```

so that the new environment for the fork can be set up appropiately.

**Comment by MelonHjy** [comment]
![image](https://user-images.githubusercontent.com/36230764/92231726-df518200-eedf-11ea-8236-399132638d39.png)
I am already save the value in a seperate class property.I need to new the driver,when I start the pytest project(So how can I use "if __name__ == '__main__': "?),But obviously i can't do it before the fork.)
![image](https://user-images.githubusercontent.com/36230764/92231825-01e39b00-eee0-11ea-8379-2bd773efaad4.png)

**Comment by bitranox** [comment]
I am afraid I cant help here - for sure it hase something to do with forking behaviour under windows.
Since python needs to emulate a forking-like behaviour on windows, You need to check in this direction ...
