### ISSUE TITLE
Support for with-statement would be nice

### ISSUE THREAD

**Issue by guettli** [bitranox/wrapt_timeout_decorator#28]
* **I'm submitting a ... **

  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**

```
def check_celery(app_configs, **kwargs):
    with timeout(3):
        dummy_task.delay()
```

```
  File "/home/guettli/projects/lala-env/src/lala/checks.py", line 9, in check_celery
    with timeout(3):
AttributeError: 'function' object has no attribute '__enter__'
```

* **What is the expected behavior?**

 I would like timeout() to work in a with-statement, too.

* **What is the motivation / use case for changing the behavior?**

I think this is simplifies my use-case.

* **Please tell us about your environment:**

wrapt-timeout-decorator==1.3.1

**Comment by bitranox** [comment]
Thomas, good idea !
I will implement it, though that will take some time
yoursa sincerely
Robert

**Comment by bitranox** [comment]
I checked, but that is NOT possible. We need to decorate a function with a certain result - therefore we cant just work on a context.
Your request is simply not possible.
