### ISSUE TITLE
timout decorator fails in a loop

### ISSUE THREAD

**Issue by SpangeJ** [bitranox/wrapt_timeout_decorator#30]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
A simple sleep example loops fine, but a more sophisticated example using Basler PyPylon (SwigPyObjects) fails the SECOND time in my loop

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Please observe this simple example
```
import sys
from time import sleep
from wrapt_timeout_decorator import timeout
@timeout(dec_timeout=None, use_signals=False, timeout_exception=TimeoutError,
         dec_allow_eval=False, dec_hard_timeout=False)
def really_long_function():
    print("Really long function Start")
    sleep(3.1415)
    print("Really long function END")
    return True

argv = sys.argv
var = float(argv[1]) if len(argv) > 1 else 2
print('INIT')
while True:
    result = really_long_function(dec_timeout=var, use_signals=False)
```
Running:
`python timeout_test.py 2` 
Results in a timeout
`python timeout_test.py 4` 
Result in an indefinite loop.
So far so good.

Now look at this example:
```
import sys
from pypylon import pylon
from time import sleep
from wrapt_timeout_decorator import timeout, detect_unpickable_objects


@timeout(dec_timeout=None, use_signals=False, timeout_exception=TimeoutError,
         dec_allow_eval=False, dec_hard_timeout=False)
def _test_device():
    print("Starting Test")
    devices = pylon.TlFactory.GetInstance().EnumerateDevices()
    print('Test Passed: Device enumerate')
    GI = pylon.TlFactory.GetInstance().CreateDevice(devices[0])
    print('Test Passed: Create Device')
    camera = pylon.InstantCamera(GI)
    print('Test Passed: Instantiate Device')
    camera.Open()
    print('Test Passed: Camera Opened')
    sleep(1)
    camera.Close()
    print('Test Passed: Camera Closed')


def open_device():
    devices = pylon.TlFactory.GetInstance().EnumerateDevices()
    print('Device enumerate OK')
    GI = pylon.TlFactory.GetInstance().CreateDevice(devices[0])
    print('Create Device OK')
    camera = pylon.InstantCamera(GI)
    camera.Open()
    print('Camera Opened')
    return camera


def close_device(c):
    c.Close()
    print('Camera Closed')


argv = sys.argv
var= float(argv[1]) if len(argv) > 1 else 2
print('INIT')
while True:
    try:
        _test_device(dec_timeout=var, use_signals=False)
        sleep(1)
        print('All tests passed!')
    except TimeoutError as EXX:
        print(EXX)
        print('Something Wrong with the cameras, cannot connect!')
    except TypeError as EXX:
        print(EXX)
        print('Timeout Decorater cannot handle SwigPyObject, the software cannot return anything')
    else:
        cam = open_device()
        sleep(2)
        close_device(cam)
    sleep(5)
```
Pretty much the same script, but the output here is:

```
INIT
Starting Test
Test Passed: Device enumerate
Test Passed: Create Device
Test Passed: Instantiate Device
Test Passed: Camera Opened
Test Passed: Camera Closed
All tests passed!
Device enumerate OK
Create Device OK
Camera Opened
Camera Closed
Starting Test
Function _test_device timed out after 4.0 seconds
Something Wrong with the cameras, cannot connect!
```

So some weird behaviour here where the timeout decorator passes the first time but results in a timeout on the second.
Any thoughts?

* **What is the expected behavior?**
I would expect this to be another indefinite loop. There are no issues with how I close/destroy the camera object because if I do not run the `_test_device` decorated function behaviour is bug-free-

* **What is the motivation/use case for changing the behaviour?**
I am trying to run a [PyPylon](https://github.com/basler/pypylon) command that freezes python indefinitely without any timeout.
Only `CTRL + Z and sudo kill -9 {PID}` are able to stop my SW.
The bug is also reported as an [issue at PyPylon](https://github.com/basler/pypylon/issues/352)

* **Please tell us about your environment:**

- Version of wrapt_timeout_decorator : 
- Python Version:  3.6.9
- OS, OS Version:  Ubuntu 18.04 aarch 64 Jetson Xavier

**Comment by bitranox** [comment]
Dear Spange, 
this is not really a timeout decorator issue - I guess some race condition, opening another fork while the first one is not terminated completely.

1 - try to comment out the decorator on function `_test_device()` to see if it works or not, and where it fails.
keep in mind that this will fork - maybe put another `sleep(2)` after `close_device(cam)` in order to give some time to terminate the fork properly.
2 - use the decorator on the smallest possible scope.

on pylon You reported : 

Every now and then Python freezes on the command:
` camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice()) `

but in Your example You only used  `CreateDevice(devices[0])` (without checking if there are devices ... ) ??
so better You make a function that only returns that camera object and decorate THAT function with the generator.
the basic meaning is : only decorate what is ABSOLUTELY necessary and unavoidable.

yours sincerely
bitranox

**Comment by SpangeJ** [comment]
Hi Robert
Commenting out the decorator results in that the program works.

The code
```
devices = pylon.TlFactory.GetInstance().EnumerateDevices()
print('Test Passed: Device enumerate')
GI = pylon.TlFactory.GetInstance().CreateDevice(devices[0])
print('Test Passed: Create Device')
camera = pylon.InstantCamera(GI)
```
is just a way to split up the command
`camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())`
such that I can detect which sub-command that might freeze.
(It is `GI = pylon.TlFactory.GetInstance().CreateDevice(devices[0])`)

So I did what you said, I edited `_test_device()` to:
```
@timeout(dec_timeout=None, use_signals=False, timeout_exception=TimeoutError,
         dec_allow_eval=False, dec_hard_timeout=False)
def _test_device():
    print("Starting Test")
    camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
```

Still the same result. Timeout on the second run.
As you can see in my original script I got a `sleep(5)` after `close_device()`

P.S:
If I let `use_signals=True` the script works, but then it freezes indefinitely in the other machine which freezes on the `camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())` command. So that is not an option.

P.P.S:
If I don't declare `dec_timeout` (i.e. None) the script works, but then it freezes indefinitely in the other machine which freezes on the `camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())` command. So that is not an option.
Could there be a bug with the `dec_timeout` when the decorator is re-called

**Comment by bitranox** [comment]
Dear Spange,
You use `use_signals=False`, that means we use multiprocessing.
So there is another process, which is obviously not cleaning up completly or leaving some hardware in an unwanted state.
You can easily imagine that there might be resources which can not be accessed from two processes at the same time.

When using multiprocessing, the decorated function should not reside in the main module - but a different module,
AND You should guard the main part with 

```
if __name__ == '__main__':
    ...
```

please read:   [https://pypi.org/project/wrapt-timeout-decorator/#use-with-windows](url)


You got it somehow wrong - You should NARROW DOWN the scope of the decorated part.
and then, extract that part and decorate ONLY THAT PART.

```
# You should find out WHICH of that lines is hanging
devices = pylon.TlFactory.GetInstance().EnumerateDevices()
print('Test Passed: Device enumerate')
GI = pylon.TlFactory.GetInstance().CreateDevice(devices[0])
print('Test Passed: Create Device')
camera = pylon.InstantCamera(GI)
```

out of curiosity, let me know when You have found the solution

yours sincerely

Robert
