### ISSUE TITLE
Doesn't work with decorators

### ISSUE THREAD

**Issue by renero** [bitranox/wrapt_timeout_decorator#31]
When using it with a decorator like:

```python
import time
from wrapt_timeout_decorator import *

@timeout(1)
def sleeper(s):
    for j in range(10):
        time.sleep(s)
        yield j

for j in sleeper(2):
    print(j)
```

It produces an error: `TypeError: cannot pickle 'generator' object`

**Comment by bitranox** [comment]
yes - it behaves absolutely correct. in order to use the timeout decorator, the function needs to be pickable (when using signals =false)
