### ISSUE TITLE
wrapt_timeout_decorator on pypi has outdated dependencies

### ISSUE THREAD

**Issue by mcoughlin** [bitranox/wrapt_timeout_decorator#37]
Ok so I think I finally understand what is going on. When loading from pypi:

pip install wrapt-timeout-decorator
Collecting wrapt-timeout-decorator
  Using cached wrapt_timeout_decorator-1.3.1-py3-none-any.whl (17 kB)
Collecting pathlib
  Using cached pathlib-1.0.1-py3-none-any.whl
Collecting multiprocess
  Using cached multiprocess-0.70.12.2-py39-none-any.whl (128 kB)
Collecting wrapt
  Using cached wrapt-1.13.3-cp39-cp39-macosx_10_9_x86_64.whl (33 kB)
Collecting dill
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Installing collected packages: dill, wrapt, pathlib, multiprocess, wrapt-timeout-decorator
Successfully installed dill-0.3.4 multiprocess-0.70.12.2 pathlib-1.0.1 wrapt-1.13.3 wrapt-timeout-decorator-1.3.1

pathlib is installed. I think pypi could use a new release.

**Comment by bitranox** [comment]
yes - I will release soon - just need to upgade some files because my travis pipeline is broken --> moved to github actions ... 
yours sincerely
bitranox

**Comment by piehld** [comment]
`pathlib` shouldn't need to be installed from a third party—it's included in the standard python library. @mcoughlin or @bitranox, did you discover which dependency is requiring pathlib? 

This is causing a build issue in several of our PyPI projects, when including wrapt_timeout_decorator in our requirements.txt.

**Comment by mcoughlin** [comment]
@piehld I think it is wrapt_timeout_decorator itself, in the version currently on pypi.

**Comment by piehld** [comment]
Thanks @mcoughlin. That's strange then, since we only first started observing this issue in the past week, but it doesn't look like a new version of wrapt_timeout_decorator has been released on PyPI in past two years (still version 1.3.1).

Maybe the issue is with something else in our pipeline then...

**Comment by bitranox** [comment]
I will make a new release today,
then lets see if its going away ... 
yours sincerely
bitranox

**Comment by bitranox** [comment]
check the newest release - it should be solved.
https://github.com/bitranox/wrapt_timeout_decorator/releases/tag/v1.3.2

**Comment by piehld** [comment]
Thank you! Builds great on our end.
