### ISSUE TITLE
Nested timeout on Linux

### ISSUE THREAD

**Issue by Jsooooooo** [bitranox/wrapt_timeout_decorator#40]
I use nested timeout, outer function has use_signal=false and inner functions have use_signal=false too. It works on Ubuntu 20, but that will produce many processes, their parent process is 1.  But these processes are not zombie, and process 1 will not recycle them. So i think maybe the outer function has timeout and inner function hasn't finished causes the result. Then i use crontab to kill these processes, and i want to know is there a pythonic solution?

**Comment by bitranox** [comment]
Dear [Jsoo](https://github.com/Jsooooooo),
If the parent is about to die, it is the parents job to clean up (send `SIGTERM`) all his childs.
The child needs to properly terminate on `SIGTERM`, or You need to send `SIGKILL` to the child.
this all can be done in the python code.

You might also read : [propagate Sigterm](https://stackoverflow.com/questions/34518233/what-would-cause-a-sigterm-to-not-propagate-to-child-processes)

yours sincerely
bitranox

**Comment by Jsooooooo** [comment]
Thanks for your link, and i will send SIGTERM to pgid rather than pid.
