### ISSUE TITLE
Does not work with nested functions with timeout

### ISSUE THREAD

**Issue by chirag127** [bitranox/wrapt_timeout_decorator#43]

**Comment by bitranox** [comment]
so what was the solution ? enlighten me, what was the problem ?

**Comment by chirag127** [comment]
> so what was the solution ? enlighten me, what was the problem ?

I have provided the test code.

**Comment by bitranox** [comment]
so - You still have the problem ? so why You close it then ?

**Comment by sem-hub** [comment]
So, where is code?

**Comment by bitranox** [comment]
give me an example code !

**Comment by sem-hub** [comment]
I asked the same from [chirag127]

**Comment by bitranox** [comment]
@sem-hub I thought You ask ME ...
