### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by yairVanti** [bitranox/wrapt_timeout_decorator#44]
![image](https://user-images.githubusercontent.com/101978729/215323654-d14c8ab7-bdc2-418a-a323-ca29153857ba.png)

![image](https://user-images.githubusercontent.com/101978729/215323716-94471f40-01e5-4941-b209-1b438ef43d5d.png)

found with pipdeptree

- Version of wrapt_timeout_decorator : 1.3.12.2
- Python Version : 3.9
- OS, OS Version : macOs 13.1

**Comment by bitranox** [comment]
dear @yairVanti ,

thank You for the report - it is resolved.

yours sincerely

bitranox
