### ISSUE TITLE
Thank you! Works on amazing on both macOS and Windows

### ISSUE THREAD

**Issue by unfor19** [bitranox/wrapt_timeout_decorator#47]
Just wanted to say thank you 🙏

I developed scripting automation to manipulate [Audacity](https://www.audacityteam.org/), and since Audacity uses pipes to "expose its [Scripting API](https://manual.audacityteam.org/man/scripting_reference.html)" it's challenging to work with.

To be specific about why this [wrapt_timeout_decorator](https://github.com/bitranox/wrapt_timeout_decorator) package is so excellent - I had endless issues dealing with random freezes due to Windows pipes `'\\.\pipe\ToSrvPipe'  '\\.\pipe\FromSrvPipe'`, and `'/tmp/audacity_script_pipe.to.UUID' '/tmp/audacity_script_pipe.from.UUID'` on macOS.

Using `open(file_path, 'r')` or even `os.open(file_path, O_RDONLY | O_NONBLOCK)` in a `try except` block is useless, at least in my case with *Audacity*, as it freezes; even `os.path.exists(file_path)` freezes in some cases.

The best way to handle that kind of freeze is to set a `timeout` and retry until the pipe is available for the next command. That is especially true for automation that is not customer-facing but is for self-use and productivity.

In general, I would avoid timeouts in my application because it means I am missing a bigger issue; but, and that's a big **BUT**, if my application needs to handle random access to read and write (I/O operations) to pipes or files that are not necessarily available all the time, then using `wrapt_timeout_decorator` is my go-to from now on.

Here's how I used it in my app, added **two lines of code**, and that's it :)

[audacity-scripting - src/audacity_scripting/bridge/pipe.py](https://github.com/unfor19/audacity-scripting/commit/230c0bc392fc8e0bd58f5ce19f98ce359b39b939) 
```python
from wrapt_timeout_decorator import timeout

@timeout(7)  # Lucky Number Slevin (2006)
def do_command_(CMD='GetInfo: Preferences', sleep_seconds=0.03):
    # Initialize variables for Windows and macOS/Linux
    # Pipe names and EOL is set according to - https://manual.audacityteam.org/man/scripting.html
    time.sleep(sleep_seconds)
    pipe_name_send = ''
    pipe_name_from = ''
    # .. Rest of code
```

**Comment by bitranox** [comment]
glad it worked out for You. spread the word ;-)

**Comment by bitranox** [comment]
and maybe narrow down the scope of the timeout decorator - just decorate what is ABSOLUTELY neccessary !.
yours sincerely from Vienna
Robert

**Comment by unfor19** [comment]
Thank you! Will do!
