### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [bitranox/wrapt_timeout_decorator#59]
In the locations listed below, there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except:` clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

https://github.com/bitranox/wrapt_timeout_decorator/blob/092bdc6e38b1dbfe9afe78877412508551390279/wrapt_timeout_decorator/wrap_helper.py#L155
https://github.com/bitranox/wrapt_timeout_decorator/blob/092bdc6e38b1dbfe9afe78877412508551390279/wrapt_timeout_decorator/wrap_helper.py#L174
https://github.com/bitranox/wrapt_timeout_decorator/blob/092bdc6e38b1dbfe9afe78877412508551390279/wrapt_timeout_decorator/wrap_helper.py#L185

**Comment by bitranox** [comment]
Dear Irit,
it is meant to be like that. Those functions should not raise, but return the unpickable objects. Those functions are purely for diagnostic purposes during development and therefore dont raise, but just return the objects which seem to be not pickable.
Yours sincerely
Bitranox

**Comment by iritkatriel** [comment]
Should it be `except BaseException:` instead of `except Exception:` then?

**Comment by bitranox** [comment]
the exceptions i saw with that modules where alway subclasses of `Exception` but its a valid point to use `BaseException`.  I will change that and put some comments to make the intentions more clear there, thanks !
